# Generated by Django 5.0.4 on 2024-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(),
        ),
    ]
